# -*- coding: utf-8 -*-
"""comp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOMOh_t9lw8ULTj-N5ncTFtuLNg5c_cL
"""

import pandas as pd
import numpy as np

df_raw = pd.read_excel("data_cleaning_practice_10_columns.xlsx")

df_raw

df_raw.isnull().sum()

import pandas as pd
import numpy as np

def clean_data_project(df_raw):

    df = df_raw.copy()

    # ============================
    # 1) Numeric Columns
    # ============================
    numeric_cols = ['age', 'income', 'orders_count', 'session_time_min']

    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].fillna(df[col].median())

        # Outlier capping
        upper = df[col].quantile(0.99)
        df[col] = df[col].clip(upper=upper)

    # ============================
    # 2) Categorical Columns
    # ============================
    categorical_cols = ['city', 'product', 'payment_method']

    for col in categorical_cols:
        df[col] = df[col].astype(str).str.lower().str.strip()

        # Clean invalid values
        df[col] = df[col].replace(
            ['nan', 'n/a', 'none', 'unknown', ''],
            'unknown'
        )

    # Canonical city names
    city_map = {
        'riyadh': 'riyadh',
        'riaydh': 'riyadh',
        'riyad': 'riyadh',
        'mecca': 'mecca',
        'makkah': 'mecca',
        'dammam': 'dammam',
        'jeddah': 'jeddah',
        'unknown': 'unknown'
    }
    df['city'] = df['city'].apply(lambda x: city_map.get(x, 'unknown'))

    # ============================
    # 3) Customer Rating
    # ============================
    df['customer_rating'] = df['customer_rating'].astype(str)

    df['customer_rating'] = df['customer_rating'].replace(
        ['N/A', 'n/a', 'unknown', 'nan', ''],
        np.nan
    )

    df['customer_rating'] = pd.to_numeric(df['customer_rating'], errors='coerce')
    df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].median())

    # ============================
    # 4) Date Columns (set to unknown)
    # ============================
    df['signup_date'] = 'unknown'
    df['last_purchase_date'] = 'unknown'

    # ============================
    # 5) Final Type Casting
    # ============================
    df['city'] = df['city'].astype('category')
    df['product'] = df['product'].astype('category')
    df['payment_method'] = df['payment_method'].astype('category')

    return df


# ============================
# Run with chunks
# ============================

df_raw = pd.read_excel("data_cleaning_practice_10_columns.xlsx")

chunk_size = 500
cleaned_chunks = []

for start in range(0, len(df_raw), chunk_size):
    end = start + chunk_size
    chunk = df_raw.iloc[start:end]
    cleaned_chunk = clean_data_project(chunk)
    cleaned_chunks.append(cleaned_chunk)

df_clean = pd.concat(cleaned_chunks, ignore_index=True)

print(df_clean.head())
print(df_clean.info())

df_raw.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns

#FOR EDA
# Boxplots for numeric columns
for col in numeric_cols:
    plt.figure(figsize=(8,4))
    sns.boxplot(x=df_clean[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

# Scatterplot: income vs orders_count
plt.figure(figsize=(8,6))
sns.scatterplot(x="income", y="orders_count", data=df_clean)
plt.title("Income vs Orders Count")
plt.show()