# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-jDPnF-6YM0PACqt6Jn9gqjKVBImEhU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ========== 1) قراءة البيانات ==========
df_raw = pd.read_excel("data_cleaning_practice_10_columns.xlsx")

# ========== 2) تنظيف بسيط (نفس منطقك السابق تقريباً) ==========
def clean_data_project(df_raw):
    df = df_raw.copy()

    # Numeric columns
    numeric_cols = ['age', 'income', 'orders_count', 'session_time_min']
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        df[col] = df[col].fillna(df[col].median())

    # Categorical columns
    categorical_cols = ['city', 'product', 'payment_method']
    for col in categorical_cols:
        df[col] = df[col].astype(str).str.lower().str.strip()
        df[col] = df[col].replace(['nan', 'n/a', 'none', 'unknown', ''], 'unknown')

    # customer_rating
    df['customer_rating'] = df['customer_rating'].astype(str)
    df['customer_rating'] = df['customer_rating'].replace(
        ['nan', 'n/a', 'unknown', ''], np.nan
    )
    df['customer_rating'] = pd.to_numeric(df['customer_rating'], errors='coerce')
    df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].median())

    return df

df_clean = clean_data_project(df_raw)

# ========== 3) تعريف الأعمدة الرقمية للـ EDA ==========
numeric_cols = ['age', 'income', 'orders_count', 'session_time_min']

# ========== 4) Boxplots ==========
for col in numeric_cols:
    plt.figure(figsize=(8,4))
    sns.boxplot(x=df_clean[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

# ========== 5) Scatterplot: income vs orders_count ==========
plt.figure(figsize=(8,6))
sns.scatterplot(x="income", y="orders_count", data=df_clean)
plt.title("Income vs Orders Count")
plt.show()


"""LARA AND SHAHAD"""
