# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBYzdrW_2EFS6AOE7N9qr-v0eX9Fdbl6
"""

import numpy as np

feature = np.array([30.0, 50.0, 10.0])
weights = np.array([0.05, 0.8, -0.1])

sum_vec = feature + weights
scaled = 0.1 * weights

print("feature:", feature, "shape:", feature.shape)
print("weights:", weights, "shape:", weights.shape)
print("sum:", sum_vec)
print("scaled:", scaled)
print("||feature||:", np.linalg.norm(feature))
print("||weights||:", np.linalg.norm(weights))

a = np.array([1.0, 2.0, 3.0])
b = np.array([0.5, 1.0, 1.5])

dot = a @ b
cos = dot / (np.linalg.norm(a) * np.linalg.norm(b))

print("a:", a)
print("b:", b)
print("dot:", dot)
print("cosine similarity:", cos)

X = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
])
W = np.array([
    [0.1, -0.2],
    [0.4, 0.0],
    [-0.3, 0.5],
])

Y = X @ W

print("X shape:", X.shape)
print("W shape:", W.shape)
print("Y shape:", Y.shape)
print("Y:", Y)
print("X.T shape:", X.T.shape)

s = np.array([
    [3.0, 4.0],
    [1.0, 2.0],
    [0.0, 5.0],
])

row_norms = np.linalg.norm(s, axis=1, keepdims=True)
s_normalized = s / row_norms

print("Row norms:", row_norms.ravel())
print("Normalized s:", s_normalized)
print("Norms after:", np.linalg.norm(s_normalized, axis=1))

u = np.array([
    [1.0, 0.5],
    [2.0, -1.0],
    [0.0, 3.0],
])
o = np.array([
    [0.2, -0.1, 0.5],
    [0.7, 0.3, -0.2],
])
b = np.array([0.1, 0.0, -0.3])

p = u @ o + b

print("u shape:", u.shape)
print("o shape:", o.shape)
print("b shape:", b.shape)
print("p shape:", p.shape)
print("p:", p)